#!python

import pygame
import sys
import random
from options import Option

HEAT_BAR_IMAGE = pygame.Surface((1000, 10))

class Game:
    def __init__(self):
        self.gameState = 1
        self.score = 0
        self._exit = False
        self.gameDisplay = pygame.display.set_mode((1200, 859))
        self.menuFont = pygame.font.Font("assets/font/wayner.ttf", 40)
        self.options = [Option("PLAY", (540, 510), self.menuFont, self.gameDisplay),
                        Option("OPTIONS", (505, 575), self.menuFont, self.gameDisplay),
                        Option("EXIT", (548, 635), self.menuFont, self.gameDisplay)]
        self.volume = 100
        pygame.mixer.music.load("assets/music/intro.ogg")
        pygame.mixer.music.play()

    def getExit(self):
        return self._exit

    def setExit(self, status):
        self._exit = status

    def setBackground(self, x, y):
        self.gameDisplay.blit(pygame.image.load("assets/images/background.jpg"), (x, y))

    def setGeometrics(self):
        geomtrics = [
            pygame.image.load("assets/images/cube.png"),
            pygame.image.load("assets/images/delta.png"),
            pygame.image.load("assets/images/losange.png"),
            pygame.image.load("assets/images/rond.png"),
            pygame.image.load("assets/images/star.png"),
            pygame.image.load("assets/images/background_game.jpg")
        ]
        return (geomtrics)

    def isHover(self, listOptions):
        for option in listOptions:
            option.is_hovered = True if option.rect.collidepoint(pygame.mouse.get_pos()) else False
            option.draw(self.gameDisplay, self.menuFont)

    def handlerMenu(self):
        ORANGE = 255, 100, 0
        self.setBackground(0, 0)
        pygame.event.pump()
        self.isHover(self.options)
        bigText = pygame.font.Font("assets/font/ka1.ttf", 35)
        title_text = bigText.render("PREVIOUS SCORE - " + str(self.score), True, ORANGE)
        self.gameDisplay.blit(title_text, (350, 700))
        if (pygame.mouse.get_pressed()[0] and self.options[0].rect.collidepoint(pygame.mouse.get_pos())):
            pygame.mixer.music.load("assets/music/on-the-run.ogg")
            pygame.mixer.music.play()
            self.gameHandler()
            pygame.mixer.music.load("assets/music/intro.ogg")
            pygame.mixer.music.play()
        if (pygame.mouse.get_pressed()[0] and self.options[1].rect.collidepoint(pygame.mouse.get_pos())):
            self.gameDisplay.fill((0,0,0))
            self.optionHandler()
        if (pygame.mouse.get_pressed()[0] and self.options[2].rect.collidepoint(pygame.mouse.get_pos())):
            sys.exit(0)

    def optionHandler(self):
        self.menuFont = pygame.font.Font("assets/font/ka1.ttf", 40)
        optionMenuFont = pygame.font.init()
        option = Option("VOLUME : " + str(self.volume), (440, 525), self.menuFont, self.gameDisplay)
        while True:
            self.gameDisplay.fill((0,0,0))
            self.setBackground(0,0)
            if self.optionEventHandler() == 1:
                return 1
            pygame.event.pump()
            title_text = self.menuFont.render("VOLUME : " + str(self.volume), True, (0, 0, 0))
            self.gameDisplay.blit(title_text, (440, 525))
            pygame.display.update()

    def optionEventHandler(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return 1
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    return 1
                if event.key == pygame.K_m and self.volume == 100:
                    self.volume = 0
                    pygame.mixer.music.set_volume(self.volume)
                else:
                    self.volume = 100
                    pygame.mixer.music.set_volume(self.volume)

    def bar(self):
        color = pygame.Color('#f22b2b')
        for x in range(HEAT_BAR_IMAGE.get_width()):
            for y in range(HEAT_BAR_IMAGE.get_height()):
                HEAT_BAR_IMAGE.set_at((x, y), color)
            if x > 200:
                color = pygame.Color('#f2b11a')
            if x > 400:
                color = pygame.Color('#e0e00f')
            if x > 600:
                color = pygame.Color('#2dc611')

    def position(self, LIST):
        tmp = None
        idx = 0
        pos = [
            [20, 30, False, 0],
            [260, 50, False, 1],
            [510, 50, False, 2],
            [760, 50, False, 3],
            [1010, 50, False, 4],
        ]
        while idx < 5:
            tmp = pos[random.randint(0, 4)]
            if (tmp[2] == True):
                continue
            LIST[idx][0] = tmp[0]
            LIST[idx][1] = tmp[1]
            LIST[idx][2] = tmp[3]
            tmp[2] = True
            idx += 1

    def check_key(self, idx, key, LIST):
        tmp = 0

        while (tmp < 5):
            if LIST[tmp][2] == idx:
                if LIST[tmp][3] != key:
                    return (-1)
            tmp += 1
        return (0)


    def gameHandler(self):
        ORANGE = 255, 100, 0
        WHITE = 255, 255, 255
        GEO = self.setGeometrics()
        GEO2 = self.setGeometrics()
        LIST = [[0, 0, 0, "A", True], [0, 0, 0, "Z", True], [0, 0, 0, "E", True], [0, 0, 0, "R", True], [0, 0, 0, "T", True]]
        self.position(LIST)
        clock = pygame.time.Clock()
        heat_rect = HEAT_BAR_IMAGE.get_rect(topleft=(100, 450))
        heat = 100
        done = False
        idx_key = 0

        self.score = 0
        while not done:
            for event in pygame.event.get():
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_ESCAPE:
                        done = True
                    if event.key == pygame.K_a:
                        if (self.check_key(idx_key, "A", LIST)) == -1:
                            idx_key = 0
                            LIST[0][4] = True
                            LIST[1][4] = True
                            LIST[2][4] = True
                            LIST[3][4] = True
                            LIST[4][4] = True
                        else:
                            LIST[0][4] = False
                            idx_key += 1
                    if event.key == pygame.K_z:
                        if self.check_key(idx_key, "Z", LIST) == -1:
                            idx_key = 0
                            LIST[0][4] = True
                            LIST[1][4] = True
                            LIST[2][4] = True
                            LIST[3][4] = True
                            LIST[4][4] = True
                        else:
                            LIST[1][4] = False
                            idx_key += 1
                    if event.key == pygame.K_e:
                        if self.check_key(idx_key, "E", LIST) == -1:
                            idx_key = 0
                            LIST[0][4] = True
                            LIST[1][4] = True
                            LIST[2][4] = True
                            LIST[3][4] = True
                            LIST[4][4] = True
                        else:
                            LIST[2][4] = False
                            idx_key += 1
                    if event.key == pygame.K_r:
                        if self.check_key(idx_key, "R", LIST) == -1:
                            idx_key = 0
                            LIST[0][4] = True
                            LIST[1][4] = True
                            LIST[2][4] = True
                            LIST[3][4] = True
                            LIST[4][4] = True
                        else:
                            LIST[3][4] = False
                            idx_key += 1;
                    if event.key == pygame.K_t:
                        if self.check_key(idx_key, "T", LIST) == -1:
                            idx_key = 0
                            LIST[0][4] = True
                            LIST[1][4] = True
                            LIST[2][4] = True
                            LIST[3][4] = True
                            LIST[4][4] = True
                        else:
                            LIST[4][4] = False
                            idx_key += 1
            if idx_key == 5:
                idx_key = 0
                heat = 100
                self.score += 1
                self.position(LIST)
                LIST[0][4] = True
                LIST[1][4] = True
                LIST[2][4] = True
                LIST[3][4] = True
                LIST[4][4] = True
            self.bar()
            heat -= 0.2 + self.score/3
            heat = max(1, min(heat, 100))
            self.gameDisplay.blit(GEO[5], (0,0))
            bigText = pygame.font.Font("assets/font/ka1.ttf", 80)
            title_text = bigText.render("SCORE: " + str(self.score), True, ORANGE)
            self.gameDisplay.blit(title_text, (380, 280))
            if LIST[0][4] == True:
                self.gameDisplay.blit(GEO[0], (LIST[0][0], LIST[0][1]))
            if LIST[1][4] == True:
                self.gameDisplay.blit(GEO[1], (LIST[1][0], LIST[1][1]))
            if LIST[2][4] == True:
                self.gameDisplay.blit(GEO[2], (LIST[2][0], LIST[2][1]))
            if LIST[3][4] == True:
                self.gameDisplay.blit(GEO[3], (LIST[3][0], LIST[3][1]))
            if LIST[4][4] == True:
                self.gameDisplay.blit(GEO[4], (LIST[4][0], LIST[4][1]))
            ##########################################
            self.gameDisplay.blit(GEO2[0], (20, 600))
            self.gameDisplay.blit(GEO2[1], (260, 620))
            self.gameDisplay.blit(GEO2[2], (510, 620))
            self.gameDisplay.blit(GEO2[3], (760, 620))
            self.gameDisplay.blit(GEO2[4], (1010, 620))
            bigText = pygame.font.Font("assets/font/ka1.ttf", 45)
            title_text = bigText.render("A", True, WHITE)
            self.gameDisplay.blit(title_text, (100, 670))
            title_text = bigText.render("Z", True, WHITE)
            self.gameDisplay.blit(title_text, (340, 692))
            title_text = bigText.render("E", True, WHITE)
            self.gameDisplay.blit(title_text, (600, 670))
            title_text = bigText.render("R", True, WHITE)
            self.gameDisplay.blit(title_text, (840, 680))
            title_text = bigText.render("T", True, WHITE)
            self.gameDisplay.blit(title_text, (1095, 687))
            self.gameDisplay.blit(HEAT_BAR_IMAGE, heat_rect, (0, 0, heat_rect.w/100*heat, heat_rect.h))
            if (heat_rect.w/100*heat) == 10:
                done = True
            pygame.display.flip()
            clock.tick(30)

def handlerEvent(game):
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit(0)
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                game.setExit(True)

def vormGame():
    pygame.init()
    pygame.display.set_caption('Vorm')
    pygame.display.set_icon(pygame.image.load('./assets/icon.png'))
    game = Game()
    while not game.getExit():
        handlerEvent(game)
        game.handlerMenu()
        pygame.display.update()
    pygame.quit()
    quit()

vormGame()